export interface Data {
    INCOME_STATEMENT: IncomeStatement
    BALANCE_SHEET: BalanceSheet
    CASH_FLOW: CashFlow
}

export interface IncomeStatement {
    REVENUE?: number
    COST_OF_REVENUE?: number
    TOTAL_OPERATING_EXPENSES?: number
    RESEARCH_AND_DEVELOPMENT?: number
    SALES_GENERAL_AND_ADMINISTRATIVE?: number
    OPERATING_INCOME?: number
    INTEREST_EXPENSES?: number
    OTHER_INCOME_EXPENSE?: number
    INCOME_BEFORE_TAXES?: number
    PROVISION_FOR_INCOME_TAXES?: number
    NET_INCOME?: number
    NET_INCOME_AVAILABLE_TO_COMMON_SHAREHOLDERS?: number
}

export interface BalanceSheet {
    TOTAL_ASSETS?: number
    TOTAL_CURRENT_ASSETS?: number
    CASH_AND_CASH_EQUIVALENTS?: number
    MARKETABLE_SECURITIES?: number
    RECEIVABLES?: number
    INVENTORIES?: number
    INCOME_TAX_RECEIVABLE?: number
    OTHER_CURRENT_ASSETS?: number
    TOTAL_NON_CURRENT_ASSETS?: number
    NET_PROPERTY_PLANT_AND_EQUIPMENT?: number
    PROPERTY_AND_EQUIPMENT_AT_COST?: number
    ACCUMULATED_DEPRECIATION?: number
    INVESTMENTS?: number
    INTANGIBLE_ASSETS?: number
    DEFERRED_INCOME_TAXES_NON_CURRENT_ASSETS?: number
    GOODWILL?: number
    OTHER_LONG_TERM_ASSETS?: number
    TOTAL_LIABILITIES_AND_STOCKHOLDERS_EQUITY?: number
    TOTAL_LIABILITIES?: number
    TOTAL_CURRENT_LIABILITIES?: number
    SHORT_TERM_DEBT?: number
    CAPITAL_LEASES_CURRENT_LIABILITIES?: number
    ACCOUNTS_PAYABLE?: number
    TAXES_PAYABLE?: number
    DEFERRED_INCOME_TAXES_CURRENT_LIABILITIES?: number
    ACCURED_LIABILITIES?: number
    EMPLOYEE_COMPENSATION_AND_BENEFITS?: number
    OTHER_CURRENT_LIABILITIES?: number
    TOTAL_NON_CURRENT_LIABILITIES?: number
    LONG_TERM_DEBT?: number
    CAPITAL_LEASES_NON_CURRENT_LIABILITIES?: number
    DEFERRED_TAXES_LIABILITIES?: number
    OTHER_LONG_TERM_LIABILITIES?: number
    TOTAL_COMPANY_STOCKHOLDERS_EQUITY?: number
    COMMON_STOCK?: number
    RETAINED_EARNINGS?: number
    ACCUMULATED_OTHER_COMPREHENSIVE_INCOME?: number
}

export interface CashFlow {
    NET_CASH_PROVIDED_BY_OPERATING_ACTIVITIES?: number
    NET_INCOME_CASH_FLOW?: number
    DEFERRED_INCOME_TAXES?: number
    SHARE_BASED_COMPENSATION?: number
    ASSET_IMPAIMENT?: number
    ACCOUNTS_RECEIVABLE?: number
    ACCOUNTS_PAYABLE_CASH_FLOW?: number
    DEFERRED_CREDITS_AND_OTHER_LIABILITIES?: number
    NET_CASH_USED_FOR_INVESTING_ACTIVITIES?: number
    INVESTMENT_IN_PROPERTY_PLANT_AND_EQUIPMENT?: number
    OTHER_INVESTING_CHARGES?: number
    NET_CASH_USED_FOR_FINANCING_ACTIVITIES?: number
    COMMON_STOCK_REPURCHASED?: number
    EFFECT_OF_EXCHANGE_RATE_CHANGES?: number
    CASH_AT_BEGINNING_OF_PERIOD?: number
    CASH_AT_END_OF_PERIOD?: number
    CASH_PAID_FOR_INCOME_TAXES?: number
}
